name: Haskell CI

env:
  EXECUTABLE: foobar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Cache .stack-work
      uses: actions/cache@v2
      env:
        cache-name: stack-work
      with:
        path: .stack-work/
        key: ${{ runner.os }}-cache-${{ env.cache-name }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('stack.yaml') }}
    - name: Cache .stack
      uses: actions/cache@v2
      env:
        cache-name: stack
      with:
        path: .stack
        key: ${{ runner.os }}-cache-${{ env.cache-name }}
    - name: Setup Stack
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        STACK_ROOT: github.workspace
      uses: mstksg/setup-stack@v2
    - name: Build
      env:
        STACK_ROOT: github.workspace
      run: stack build
    - name: Run tests
      env:
        STACK_ROOT: github.workspace
      run: stack test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-${{ env.EXECUTABLE }}
        path: .stack-work/install/*/*/*/bin/*